FROM python:3.9.9-alpine

RUN apk update \
	&& apk add --no-cache --virtual build-deps gcc python3-dev musl-dev \
	mariadb-dev build-base libffi-dev \
	&& apk add --no-cache jpeg-dev zlib-dev libjpeg \
	&& apk add --no-cache python3 py3-pip py-cffi

COPY ../requirements /app/requirements

WORKDIR /app

RUN pip3 install --upgrade pip \
	&& pip3 install --no-cache-dir -r requirements/dev.txt \
	&& apk del build-deps

COPY ../. /app/

ENV DJANGO_READ_DOT_ENV_FILE 1
ENV DJANGO_SETTINGS_MODULE askallery.settings.base

RUN python3 manage.py collectstatic --noinput

CMD ["gunicorn", "--bind", "0.0.0.0:$PORT", "askallery.wsgi", "--chdir=/app"]
