version: "3.7"

services:
    app:
        build: 
            context: ..
            dockerfile: ./Dockerfile
        image: askallery-api
        volumes:
            - ..:/app
        ports:
            - "8000:8000"
        environment: 
            PORT: 8000
            PYTHONUNBUFFERED: 1
        command: "python manage.py runserver 0.0.0.0:8000"
